# Generated by Django 2.0.2 on 2018-02-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_item_marked'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='name',
            field=models.CharField(default='your list', max_length=300),
        ),
    ]
