# Generated by Django 2.0.2 on 2018-02-18 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_list_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
