# Generated by Django 2.0 on 2018-02-18 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20180218_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_items', to='website.List'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='list',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(default='twoja lista', max_length=300),
        ),
    ]
