# Generated by Django 2.0 on 2018-02-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20180218_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.CharField(default='', max_length=300, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(default='twoja lista', max_length=300, verbose_name=''),
        ),
    ]
