# Generated by Django 2.0 on 2018-02-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20180219_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Twoja kategoria', max_length=300, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(default='Twoja lista', max_length=300, verbose_name=''),
        ),
    ]
